spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                default-label: master
                git:
                    uri: https://github.com/ismailatac/config-server-e-commerce
    profiles:
        active: dev
server:
    port: 8888